name: C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y lcov cmake g++

    - name: Download and Install Google Test
      run: |
        sudo apt-get install libgtest-dev
        # Luo ja siirry build-hakemistoon
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        # Kopioi valmiit kirjastotiedostot
        sudo cp lib/libgtest*.a /usr/lib

    - name: Build and Test with Coverage
      run: |
        cmake -DCMAKE_BUILD_TYPE=Debug .
        make
        make test
        lcov --directory . --capture --output-file coverage.info
        lcov --remove coverage.info '/usr/*' --output-file coverage.info

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.info
        fail_ci_if_error: true
