name: C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y lcov cmake g++ python3-pip

    - name: Download and Install Google Test
      run: |
        sudo apt-get install libgtest-dev
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp lib/libgtest*.a /usr/lib

    - name: Install gcovr
      run: pip3 install gcovr

    - name: Build and Test with Coverage
      run: |
        cmake -DCMAKE_BUILD_TYPE=Debug .
        make
        make test

    - name: Generate Coverage Report
      run: gcovr -r . --html --html-details -o coverage.html

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: coverage.html
