name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y cmake g++ python3-pip

    - name: Download and Install Google Test
      run: |
        sudo apt-get install libgtest-dev
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp lib/libgtest*.a /usr/lib

    - name: Install gcovr
      run: pip3 install gcovr

    - name: Build and Test with Coverage
      run: |
        cmake -DCMAKE_BUILD_TYPE=Debug .
        make
        make test

    - name: Generate Coverage Report for Codecov
      run: gcovr -r . --xml -o coverage.xml -e src/main.cpp -e src/heap_benchmarking.cpp -e tests/binary_heap_test.cpp tests/binomial_heap_test.cpp tests/pairing_heap_test.cpp tests/d_ary_heap_test.cpp

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
